# Generated by Django 5.2.3 on 2025-06-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
